////////////////////////////////////////////////////////////
//FIXME: this source should be autogenerated (i.e. in csr.h)
////////////////////////////////////////////////////////////
#ifndef __LITESDK_CSR_DEFS__H_
#define __LITESDK_CSR_DEFS__H_

#include "csr_helpers.h"

////////////////////////////////////////////////////////////
//supported peripherals
////////////////////////////////////////////////////////////

//IMPORTANT NOTES:
// 1) register should be 'volatile' (since memory-mapped IO should never be cached by the compiler as sometimes are regular variables)
// macro LITEX_OFFSET_ASSERT can be used to check at compile time if the offset for the registers matches the definition in csr.h
// 2) structures should be *packed* at 32-bit boundaries (since 64-bit registers sometimes are not aligned to 8-byte boundaries)
// macro LITEX_PACKED32 should be used in structure definitions (only GCC support for now)





///////////////////////////////
// GPIO
///////////////////////////////

#ifdef CSR_GPIO_BASE
#define LITEGPIO_ENABLED
#define LITEGPIO_READ(s, field)		LITECSR_READ(CSR_GPIO, s, field)
#define LITEGPIO_WRITE(s, field, v)	LITECSR_WRITE(CSR_GPIO, s, field, v)
typedef LITECSR(CSR_GPIO_OE_SIZE)	litegpio_oe_t;
typedef LITECSR(CSR_GPIO_IN_SIZE)	litegpio_in_t;
typedef LITECSR(CSR_GPIO_OUT_SIZE)	litegpio_out_t;

typedef struct LITEX_PACKED32 //fields arrangement must mach order to get exact peripheral layout
{
  litegpio_oe_t		OE;
  litegpio_in_t		IN;
  litegpio_out_t	OUT;
} litegpio_t;

//offset checking
LITEX_OFFSET_ASSERT(CSR_GPIO, litegpio_t, OE);
LITEX_OFFSET_ASSERT(CSR_GPIO, litegpio_t, IN);
LITEX_OFFSET_ASSERT(CSR_GPIO, litegpio_t, OUT);
#endif //CSR_GPIO_BASE



#endif //__LITESDK_CSR_DEFS__H_
